version: "3.8"
services:
  rxjava-vertx-kotlin-seed:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    networks:
      - rxjava-vertx-kotlin-seed-network
    ports:
      - '8080:8080'

  mongodb:
    image: mongo
    volumes:
      - rxjava-vertx-kotlin-seeddb:/data/db
    networks:
      - rxjava-vertx-kotlin-seed-network
    ports:
      - '27017:27017'

volumes:
  rxjava-vertx-kotlin-seeddb:

networks:
  rxjava-vertx-kotlin-seed-network:
    driver: bridge
