version: "3.8"
services:
  rxjava-vertx-kotlin-seed:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rxjava-vertx-kotlin-seed-app
    depends_on:
      - mongodb
    network_mode: host

  mongodb:
    image: mongo
    container_name: my_mongodb
    volumes:
      - rxjava-vertx-kotlin-seeddb:/data/db
    network_mode: host

volumes:
  rxjava-vertx-kotlin-seeddb:
