version: "3.8"
services:
  zlack:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zlack-app
    depends_on:
      - mongodb
    network_mode: host

  mongodb:
    image: mongo
    container_name: my_mongodb
    volumes:
      - zlackdb:/data/db
    network_mode: host

volumes:
  zlackdb:
