version: "3.8"
services:
  zlack:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    networks:
      - zlack-network
    ports:
      - '8080:8080'

  mongodb:
    image: mongo
    volumes:
      - zlackdb:/data/db
    networks:
      - zlack-network
    ports:
      - '27017:27017'

volumes:
  zlackdb:

networks:
  zlack-network:
    driver: bridge
