version: "3.8"
services:
  zlack:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zlack-app
    depends_on:
      - mongodb
    ports:
      - "8080:8080"

  mongodb:
    image: mongo
    container_name: my_mongodb
    ports:
      - '27017:27017'
    volumes:
      - zlackdb:/data/db

volumes:
  zlackdb:
